name: Updating helm chart

on:
  push:
    tags:
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set env
      env:
        GITHUB_REF_NAME: $GITHUB_REF_NAME
      run: |
        echo '''
        apiVersion: v2
        name: alexcv
        description: Helm chart for alex.devsysop.com
        type: application
        version: 0.1.0
        appVersion: "$GITHUB_REF_NAME"
        ''' >> alexcv/Chart.yaml
        export $GITHUB_REF_NAME
        sed -i 's/__TAG__/$GITHUB_REF_NAME/g' alexcv/Chart.yaml
        cat alexcv/Chart.yaml

    #- name: Adding alexcv repo
    #  run: |
    #    helm repo add alexcv https://charts.devsysop.com/
    #- name: Getting repo list
    #  run: helm repo list
