name: Updating helm chart

on:
  push:
    tags:
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: |
        echo $GITHUB_REF_NAME; echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
        sed  's/__TAG__/$GITHUB_ENV/g' alexcv/Chart.yaml; sed  's/__TAG__/$GITHUB_ENV/g' alexcv/values.yaml

    #- name: Adding alexcv repo
    #  run: |
    #    helm repo add alexcv https://charts.devsysop.com/
    #- name: Getting repo list
    #  run: helm repo list
