name: Updating helm chart

on:
  push:
    tags:
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: |
        echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
        sed -s 's/__TAG__/$GITHUB_REF_NAME/g' alexcv/Chart.yaml; sed  's/__TAG__/$GITHUB_REF_NAME/g' alexcv/values.yaml

    #- name: Adding alexcv repo
    #  run: |
    #    helm repo add alexcv https://charts.devsysop.com/
    #- name: Getting repo list
    #  run: helm repo list
